#! /bin/sh

TOKEN_FILE=~/.aibiji/token

function initialize_token(){
	mkdir -p $(dirname ${TOKEN_FILE}) && touch ${TOKEN_FILE}
	# TODO-impl: prompt user_name stored
	read -p "Input your user name: " user_name
	read -s -p "Password: " password
	token=$(curl -X POST https://aibiji.xyz/api/v1/token -d "user_name=${user_name}&password=${password}")
	echo "$user_name $token" | tee ${TOKEN_FILE}
}

function list_recent(){
	credential=($(cat ${TOKEN_FILE}))
	curl -v "https://aibiji.xyz/api/v1/recent?user_name=${credential[0]}&access_token=${credential[1]}"
	echo ""
}

function search(){
	keywords=$1
	echo $keywords
	echo $keywords
	echo $keywords
	credential=($(cat ${TOKEN_FILE}))
	curl -G --data-urlencode "keyword=${keywords}"  "https://aibiji.xyz/api/v1/search.text?user_name=${credential[0]}&access_token=${credential[1]}"
	echo 
}

function add(){
	contents=$1
	credential=($(cat ${TOKEN_FILE}))
	curl -X POST "https://aibiji.xyz/api/v1/note?user_name=${credential[0]}&access_token=${credential[1]}" -d "note=${contents}"
}

function version(){
	echo "0.1.0"
}

function update(){
	curl https://raw.githubusercontent.com/acearth/note-cli/master/note > /tmp/note-cli-tmp
	chmod +x /tmp/note-cli-tmp
	sudo mv /tmp/note-cli-tmp /usr/local/bin/note
}

function  help(){
	echo "[ ls | configure | search | add | version | update ] must be passed"
}

if [ $# -lt 1 ]; then
	echo "use -h to see help information"
	exit
elif [ $1 = 'ls' ]; then
	list_recent
elif [ $1 = 'configure' ] || [ $1 = 'cfg' ]; then
	initialize_token
elif [ $1 = 'search' ] || [ $1 = '-s' ]; then
	#TODO-impl: multi-keywords
	shift
	#ks=$(IFS="`" eval 'echo "$*"')
	search "$*"
elif [ $1 = 'add' ] || [ $1 = '-a' ]; then
	#TODO-impl: multi-keywords
	shift
	add "$*"
elif [ $1 = 'version' ]; then
	version
elif [ $1 = 'update' ]; then
	update
elif [ $1 = '-h' ] || [ $1 = '--help' ]; then
	help
else
	echo "Need help? Visit more on https://aibiji.xyz"
fi
